# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/medsingla/Documents/Wind_Energy/Houston/HoustonV2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/medsingla/Documents/Wind_Energy/Houston/HoustonV2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/medsingla/Documents/Wind_Energy/Houston/HoustonV2/CMakeFiles /Users/medsingla/Documents/Wind_Energy/Houston/HoustonV2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/medsingla/Documents/Wind_Energy/Houston/HoustonV2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HoustonV2

# Build rule for target.
HoustonV2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HoustonV2
.PHONY : HoustonV2

# fast build rule for target.
HoustonV2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/build
.PHONY : HoustonV2/fast

# target to build an object file
cmake_pch.hxx.pch:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/cmake_pch.hxx.pch
.PHONY : cmake_pch.hxx.pch

# target to preprocess a source file
cmake_pch.hxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/cmake_pch.hxx.i
.PHONY : cmake_pch.hxx.i

# target to generate assembly for a file
cmake_pch.hxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/cmake_pch.hxx.s
.PHONY : cmake_pch.hxx.s

src/components/AlertPanel.o: src/components/AlertPanel.cpp.o
.PHONY : src/components/AlertPanel.o

# target to build an object file
src/components/AlertPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/src/components/AlertPanel.cpp.o
.PHONY : src/components/AlertPanel.cpp.o

src/components/AlertPanel.i: src/components/AlertPanel.cpp.i
.PHONY : src/components/AlertPanel.i

# target to preprocess a source file
src/components/AlertPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/src/components/AlertPanel.cpp.i
.PHONY : src/components/AlertPanel.cpp.i

src/components/AlertPanel.s: src/components/AlertPanel.cpp.s
.PHONY : src/components/AlertPanel.s

# target to generate assembly for a file
src/components/AlertPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/src/components/AlertPanel.cpp.s
.PHONY : src/components/AlertPanel.cpp.s

src/components/ControlPanel.o: src/components/ControlPanel.cpp.o
.PHONY : src/components/ControlPanel.o

# target to build an object file
src/components/ControlPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/src/components/ControlPanel.cpp.o
.PHONY : src/components/ControlPanel.cpp.o

src/components/ControlPanel.i: src/components/ControlPanel.cpp.i
.PHONY : src/components/ControlPanel.i

# target to preprocess a source file
src/components/ControlPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/src/components/ControlPanel.cpp.i
.PHONY : src/components/ControlPanel.cpp.i

src/components/ControlPanel.s: src/components/ControlPanel.cpp.s
.PHONY : src/components/ControlPanel.s

# target to generate assembly for a file
src/components/ControlPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/src/components/ControlPanel.cpp.s
.PHONY : src/components/ControlPanel.cpp.s

src/components/LiveDataPanel.o: src/components/LiveDataPanel.cpp.o
.PHONY : src/components/LiveDataPanel.o

# target to build an object file
src/components/LiveDataPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/src/components/LiveDataPanel.cpp.o
.PHONY : src/components/LiveDataPanel.cpp.o

src/components/LiveDataPanel.i: src/components/LiveDataPanel.cpp.i
.PHONY : src/components/LiveDataPanel.i

# target to preprocess a source file
src/components/LiveDataPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/src/components/LiveDataPanel.cpp.i
.PHONY : src/components/LiveDataPanel.cpp.i

src/components/LiveDataPanel.s: src/components/LiveDataPanel.cpp.s
.PHONY : src/components/LiveDataPanel.s

# target to generate assembly for a file
src/components/LiveDataPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/src/components/LiveDataPanel.cpp.s
.PHONY : src/components/LiveDataPanel.cpp.s

src/components/TelemetryPanel.o: src/components/TelemetryPanel.cpp.o
.PHONY : src/components/TelemetryPanel.o

# target to build an object file
src/components/TelemetryPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/src/components/TelemetryPanel.cpp.o
.PHONY : src/components/TelemetryPanel.cpp.o

src/components/TelemetryPanel.i: src/components/TelemetryPanel.cpp.i
.PHONY : src/components/TelemetryPanel.i

# target to preprocess a source file
src/components/TelemetryPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/src/components/TelemetryPanel.cpp.i
.PHONY : src/components/TelemetryPanel.cpp.i

src/components/TelemetryPanel.s: src/components/TelemetryPanel.cpp.s
.PHONY : src/components/TelemetryPanel.s

# target to generate assembly for a file
src/components/TelemetryPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/src/components/TelemetryPanel.cpp.s
.PHONY : src/components/TelemetryPanel.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HoustonV2.dir/build.make CMakeFiles/HoustonV2.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... HoustonV2"
	@echo "... cmake_pch.hxx.pch"
	@echo "... cmake_pch.hxx.i"
	@echo "... cmake_pch.hxx.s"
	@echo "... src/components/AlertPanel.o"
	@echo "... src/components/AlertPanel.i"
	@echo "... src/components/AlertPanel.s"
	@echo "... src/components/ControlPanel.o"
	@echo "... src/components/ControlPanel.i"
	@echo "... src/components/ControlPanel.s"
	@echo "... src/components/LiveDataPanel.o"
	@echo "... src/components/LiveDataPanel.i"
	@echo "... src/components/LiveDataPanel.s"
	@echo "... src/components/TelemetryPanel.o"
	@echo "... src/components/TelemetryPanel.i"
	@echo "... src/components/TelemetryPanel.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

